export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const EXCHANGE_SCREEN = 'EXCHANGE_SCREEN';
export const TRANSACTIONS_SCREEN = 'TRANSACTIONS_SCREEN';
export const BUY_SELL_SCREEN = 'BUY_SELL_SCREEN';
