export const COINS_STACK = 'COINS_STACK';
export const EXCHANGE_STACK = 'EXCHANGE_STACK';

export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const EXCHANGE_SCREEN = 'EXCHANGE_SCREEN';
export const TRANSACTIONS_SCREEN = 'TRANSACTIONS_SCREEN';
export const WALLETS_SCREEN = 'WALLETS_SCREEN';
export const COINS_SCREEN = 'COINS_SCREEN';
export const COIN_DETAILS_SCREEN = 'COIN_DETAILS_SCREEN';
export const EXCHANGE_DETAILS_SCREEN = 'EXCHANGE_DETAILS_SCREEN';
